### ISSUE TITLE
Dollar sign in license file causes Dart compilation error

### ISSUE THREAD

**Issue by idy** [espresso3389/flutter_oss_licenses#25]
When the license file contains a $ symbol, the generated Dart code fails to compile. This issue occurs, for example, when using Syncfusion packages such as `syncfusion_flutter_pdf`.

**Comment by idy** [comment]
![image](https://github.com/user-attachments/assets/b1c89c52-600c-4018-8633-2979c1405ffd)

**Comment by issdn** [comment]
I created a pull request but the author hasn't been active for some time so you can use my fork for now if you wish.
Just add that to dev_dependencies in pubspec.yaml:
```yaml
  flutter_oss_licenses:
    git:
      url: https://github.com/issdn/flutter_oss_licenses.git
      path: packages/flutter_oss_licenses 
```
