### ISSUE TITLE
Does not include direct dependency (Git or local) if it specifies a path

### ISSUE THREAD

**Issue by fotiDim** [espresso3389/flutter_oss_licenses#7]
Direct dependencies that specify a path are ignored. This applies both to Git and local dependencies. The camera plugin is hosted in a subdirectory so using the `path` property is inevitable.

Works
```
camera:
```

Pub get fails because the dependency is hosted in a subdirectory
```
camera:
  git:
    url: https://github.com/flutter/plugins
```

Not working
```
camera:
  git:
    url: https://github.com/flutter/plugins
    path: packages/camera/camera
```

Not working
```
local_custom_plugin:
  path: ../local_custom_plugin
```
